spring.application.name=SistemaEvento

server.port=8999

# Banco H2 em memória
spring.datasource.url=jdbc:h2:mem:eventodb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Console do H2 habilitado
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Thymeleaf UTF-8
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
spring.thymeleaf.servlet.content-type=text/html

# Fuso horário e encoding
spring.datasource.hikari.connection-init-sql=SET TIME ZONE 'America/Sao_Paulo'
spring.mvc.locale=pt_BR
spring.mvc.locale-resolver=fixed

# Outras boas práticas
server.error.include-message=always